<?php

$title = 'Login';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'index')));
$form->prepare();
?>
<div class="col-md-4 offset-md-4" align="center" style="background:#dbdbce;border-radius: 10px;">
    <?php
        echo $this->form()->openTag($form);
    ?>
    <img src="<?php echo $this->basePath('img/user.png') ?>" alt="User" width="90px" style="margin:30px;"/>

    <h2>
        <?php echo $this->escapeHtml($title); ?>
    </h2>
    

    <br/>

    <div class="Col-md-8">
        <?php echo $this->formRow($form->get('user_name')); ?>
    </div>

    <br/>

    <div class="Col-md-8">
        <?php echo $this->formRow($form->get('senha')); ?>
    </div>

    <div class="col-md-12">
        <?php 
            $msg = $this->msg;
            echo $msg; 
        ?>
    </div>
    
    <div class="col-md-12">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php 
    echo $this->form()->closeTag();
?>