<?php

$title = 'Excluir Funcionário';
$this->headTitle($title);

$funcionario_info = $this->funcionario;
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<br>
<h5>
    Tem certeza que deseja excluir este funcionário?
</h5>
<hr>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            Código
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->id; ?>
    </dd>
</div>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            Nome
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->nome; ?>
    </dd>
</div>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            Data Nasc.
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->data_nascimento; ?>
    </dd>
</div>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            PIS
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->pis_nis; ?>
    </dd>
</div>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            CPF
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->cpf; ?>
    </dd>
</div>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            Função
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->funcao; ?>
    </dd>
</div>

<div class="col-md-12">
    <dt class="col-md-2 float-left" >
        <label class="float-right">
            Data de Cadastro
        </label>
    </dt>
    <dd class="col-md-10 float-left">
        <?php echo $this->funcionario->data_cadastro; ?>
    </dd>
</div>
<?php
$url = $this->url('funcionarios', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div class="col-md-12" style="margin-top:50px;">
    <input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
    <input type="submit" name="delete" value="Cancelar" class="btn btn-lg active col-md-2" />
    <input type="submit" name="delete" value="Excluir" class="btn btn-danger btn-lg active col-md-2" /> 
</div>
</form>