<?php
// module/Album/view/album/album/index.phtml:

$title = 'Funcionários';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="float:right;" >
    <a href="<?php echo $this->url('funcionarios', array('action'=>'create'));?>" class="btn btn-success btn-md active" role="button" aria-pressed="true">+ Adicionar novo funcionário</a>
</p>

<table class="table table-striped">
<tr>
    <th>Id</th>
    <th>Nome</th>
    <th>CPF</th>
    <th>PIS/NIS</th>
    <th></th>
</tr>
<?php foreach ($funcionarios as $funcionario) : ?>
<tr>
    <td><?php echo $this->escapeHtml($funcionario->id);?></td>
    <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
    <td><?php echo $this->escapeHtml($funcionario->cpf);?></td>
    <td><?php echo $this->escapeHtml($funcionario->pis_nis);?></td>
    <td>
        <div class="float-right">
            <a href="<?php echo $this->url('funcionarios',
                array('action'=>'update', 'id' => $funcionario->id));?>" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Alterar</a>
            <a href="<?php echo $this->url('funcionarios',
                array('action'=>'delete', 'id' => $funcionario->id));?>" class="btn btn-danger btn-sm active" role="button" aria-pressed="true">Excluir</a>
        </div>
    </td>
</tr>
<?php endforeach; ?>
</table>