<?php
$title = 'Afastar Funcionário';

$this->headTitle($title);

$funcionarios = $this->funcionarios;
?>

<h1>
<?php echo $title; ?>
</h1>
<label style="font-size:25px;color:#2c3b94;">Consultar Funcionário</label>
<br><br>
<form method="post" name="atestados" action="/afastarFuncionario/consultaFuncionarios" id="afastarFuncionario">
<div class="row form-inline form-group">

    <div  class="col-md-2 ">
        <input type="text" id="id" name="id" class="form-control" placeholder="ID" style="margin-right:5px;width:100%;">
    </div>
    <div  class="col-md-6 ">
        <input type="text" id="nome" name="nome" class="form-control" placeholder="Nome" style="width:100%">
    </div>
    <div class="col-md-4 ">
        <input type="submit" class="btn btn-md btn-primary " style="background:#0a315a;border-color:#0a315a;" value="Pesquisar">
    </div>
</div>
</form>
<table class="table table-striped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Função</th>
        <th>Data Nasc.</th>
        <th></th>
    </tr>
    <?php foreach ($funcionarios as $funcionario) : ?>
    <tr>
        <td><?php echo $funcionario->id;?></td>
        <td><?php echo $funcionario->nome;?></td>
        <td><?php echo $funcionario->funcao;?></td>
        <td><?php echo $funcionario->data_nascimento;?></td>
        <td>
            <div class="float-right">
                <a href="<?php echo $this->url('afastarFuncionario',
                    array('action'=>'create', 'id' => $funcionario->id));?>" class="btn btn-success btn-sm active"  role="button" aria-pressed="true">Afastar</a>
            </div>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>

