<?php
// module/Album/view/album/album/index.phtml:

$title = 'Afastar Funcionário';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="float:right;" >
    <a href="<?php echo $this->url('afastarFuncionario', array('action'=>'consulta-funcionarios'));?>" class="btn btn-success btn-md active" role="button" aria-pressed="true">+ Adicionar novo Atestado</a>
</p>

<table class="table table-striped">
<tr>
    <th>Código</th>
    <th>Funcionário</th>
    <th>Tipo</th>
    <th>Data de Início</th>
    <th></th>
</tr>
<?php foreach ($afastarFuncionario as $afastamento) : ?>
<tr>
    <td><?php echo $this->escapeHtml($afastamento->id);?></td>
    <td><?php echo $this->escapeHtml($afastamento->funcionario_id);?></td>
    <td><?php echo $this->escapeHtml($afastamento->tipo);?></td>
    <td><?php echo $this->escapeHtml($afastamento->data_ini);?></td>
    <td>
        <div class="float-right">
            <a href="<?php echo $this->url('afastarFuncionario',
                array('action'=>'update', 'id' => $afastamento->id));?>" class="btn btn-primary btn-sm active" style="background:#0a315a;border-color:#0a315a;" role="button" aria-pressed="true">Alterar</a>
            <a href="<?php echo $this->url('afastarFuncionario',
                array('action'=>'delete', 'id' => $afastamento->id));?>" class="btn btn-primary btn-sm active" style="background:#282829;border-color:#282829;" role="button" aria-pressed="true">Excluir</a>
        </div>
    </td>
</tr>
<?php endforeach; ?>
</table>