<?php
// module/Album/view/album/album/index.phtml:

$title = 'Teste';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('empresa', array('action'=>'create'));?>">+ Adiconar novo teste</a>
</p>

<table class="table">
<tr>
    <th>Nome</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($empresas as $empresa) : ?>
<tr>
    <td><?php echo $this->escapeHtml($empresa->id);?></td>
    <td><?php echo $this->escapeHtml($empresa->nome);?></td>
    <td>
        <a href="<?php echo $this->url('empresa',
            array('action'=>'update', 'id' => $empresa->id));?>">Edit</a>
        <a href="<?php echo $this->url('empresa',
            array('action'=>'delete', 'id' => $empresa->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>