<!DOCTYPE html>

<head>
<?php 
    use Zend\Db\ResultSet\ResultSet;
    
    echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/style.css'));
?>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery-3.4.1.min.js')
; ?>

<style type="text/css">
    .quebrapagina{
        page-break-before: always;
        page-break-inside: avoid;
    }

    @media print {
        #imprimir {
            display: none;
        }
        #voltar {
            display: none;
        }
    }
</style>
</head>

<body>

    <button class="btn btn-primary btn-lg" style="position: fixed;bottom: 150px;right:90px;" id="imprimir" aria-pressed="true" onclick="javascript:window.location.href = 'http://work-clock.localhost/relatorios/consulta-funcionarios'">Voltar</button>
    <button class="btn btn-success btn-lg" style="position: fixed;bottom: 90px;right:90px;" id="voltar" aria-pressed="true" onclick="imprimir()">Imprimir</button>

    <?php foreach($this->funcionarios->toArray() as $funcionario){?>
    <div class="col-md-6 offset-md-3" style="background-color:#f9f6f6;page-break-before: always;">
        <table>
            <tr>
                <td style="width: 100px;">
                <img width="40px" src="<?php echo $this->basePath('img/logo-login.png') ?>" alt="Zend Framework 2"/>
                </td>
                <td style="width: 500px;">
                    <div style="text-align: center;">
                        <label style="font-family: Arial;font-size:30px;">
                            Folha de Ponto
                        </label>
                        <br>
                        <label style="font-family: Arial;font-size:18px;">
                            Período: <?php echo $this->empresa['inicio']; ?> à <?php echo $this->empresa['fim']; ?>
                        </label>
                    </div>
                </td>
                <td style="width: 100px;">

                </td>
            </tr>
        </table>
        <br class="quebrapagina">
        <hr>
        <table style="font-family: Arial;font-size:11px;">
            <tr>
                <th style="text-align: right; width: 100px;">
                    Razão Social:
                </th>
                <td style="width: 230px;">
                    <?php echo $this->empresa['razao_social']; ?>
                </td>
                <th style="text-align: left; width: 55px;">
                    CNPJ:
                </th>
                <td colspan="3">
                    <?php echo $this->empresa['cnpj']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Endereço:
                </th>
                <td style="width: 230px;">
                    <?php echo $this->empresa['logradouro']; ?>
                </td>
                <th style="text-align: left; width: 55px;">
                    Número:
                </th>
                <td style="width: 90px;">
                    <?php echo $this->empresa['numero']; ?>
                </td>
                <th style="text-align: left; width: 45px;">
                    Bairro:
                </th>
                <td style="width: 70px;">
                    <?php echo $this->empresa['bairro']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    CEP:
                </th>
                <td style="width: 230px;">
                    <?php echo $this->empresa['cep']; ?>
                </td>
                <th style="text-align: left; width: 55px;">
                    Cidade:
                </th>
                <td style="width: 90px;">
                    <?php echo $this->empresa['cidade']; ?>
                </td>
                <th style="text-align: left; width: 45px;">
                    UF:
                </th>
                <td style="width: 70px;">
                    <?php echo $this->empresa['uf']; ?>
                </td>
            </tr>
        </table>
        <hr style="border: 1px solid black;">
        <table style="font-family: Arial;font-size:11px;">
            <tr>
                <th style="text-align: right; width: 100px;">
                    Código:
                </th>
                <td style="width: 230px;">
                    <?php echo $funcionario['id']; ?>
                </td>
                <th colspan="5" style="text-align: center;font-size:15px;">
                    Horário de Trabalho
                </th>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Nome:
                </th>
                <td style="width: 230px;">
                    <?php echo $funcionario['nome']; ?>
                </td>
                <th style="width: 55px;text-align: left;"> </th>
                <th colspan="2" style="text-align: center;">
                    1º Período
                </th>
                <th colspan="2" style="text-align: center;">
                    2º Período
                </th>

            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    PIS:
                </th>
                <td style="width: 230px;">
                    <?php echo $funcionario['pis_nis']; ?>
                </td>
                <th style="width: 55px;text-align: left;">
                    Dia
                </th>
                <th style="text-align: center;width: 28px;">
                    Entrada
                </th>
                <th style="text-align: center;width: 28px;">
                    Saída
                </th>
                <th style="text-align: center;width: 28px;">
                    Entrada
                </th>
                <th style="text-align: center;width: 28px;">
                    Saída
                </th>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Cargo:
                </th>
                <td style="width: 230px;">
                    <?php echo $funcionario['funcao']; ?>
                </td>
                <th style="width: 55px;text-align: left;">
                    Domingo
                </th>
                <td style="text-align: center;">
                    DSR
                </td>
                <td style="text-align: center;">
                    DSR
                </td>
                <td style="text-align: center;">
                    DSR
                </td>
                <td style="text-align: center;">
                DSR
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Salário:
                </th>
                <td style="width: 230px;">
                    <?php echo $funcionario['salario']; ?>
                </td>
                <th style="width: 55px;text-align: left;">
                    Segunda
                </th>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_2']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_2']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Admissão:
                </th>
                <td style="width: 230px;">
                    <?php echo $funcionario['data_admissao']; ?>
                </td>
                <th style="width: 55px;text-align: left;">
                    Terça
                </th>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_2']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_2']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Quarta
                </th>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_2']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_2']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Quinta
                </th>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_2']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_2']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Sexta
                </th>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_2']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_2']; ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Sábado
                </th>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_sab_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_sab_1']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['ent_sab_2']; ?>
                </td>
                <td style="text-align: center;">
                    <?php echo $this->horario['sai_sab_2']; ?>
                </td>
            </tr>

        </table>
        <hr style="border: 1px solid black;">
        <table style="font-family: Arial;font-size:11px;border:0px;border-collapse: inherit;border-spacing: 0px;">
            <tr>
                <th colspan="2"></th>
                <th colspan="2">1º Período</th>
                <th colspan="2">2º Período</th>
                <th colspan="2">3º Período</th>
                <th colspan="2">4º Período</th>
                <th colspan="2">5º Período</th>
                <th colspan="4"></th>
            </tr>
            <tr>
                <th colspan="2">Data</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 70px;">H. Trab.</th>
                <th style="text-align: center;width: 70px;">H. Abonada</th>
                <th style="text-align: center;width: 70px;">H. Falt.</th>
                <th style="text-align: center;width: 70px;">H. Extra</th>
            </tr>
            <!-- PONTOS -->
            <?php 
            //unset($i_pontos);
            //$i_pontos = $this->pontos;

            foreach($pontos as $ponto){

                if($ponto['funcionario'] == $funcionario['id'])
                {   
            ?>
                <tr style="background: #e6e6e6;">
                    <th style="text-align: left;width: 30px;"><?php echo $ponto['data'];?></th>
                    <th style="text-align: left;width: 30px;"><?php echo $ponto['dia'];?></th>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['ent_1'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['sai_1'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['ent_2'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['sai_2'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['ent_3'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['sai_3'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['ent_4'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['sai_4'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['ent_5'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['sai_5'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['trabalhadas'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['abonadas'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['faltas'];?></td>
                    <td style="text-align: center;width: 30px;"><?php echo $ponto['extra'];?></td>
                </tr>
            <?php 
                }
            }
            ?>
            <tr>
                <th colspan="2" style="text-align: left;width: 30px;">D. Trab.: <?php echo $funcionario['dias'];?></th>
                <th colspan="2" style="text-align: left;width: 30px;">D. Falt.: <?php echo $funcionario['dias_faltas'];?></th>
                <th colspan="2" style="text-align: left;width: 30px;">DSR: <?php echo $funcionario['dsr'];?></th>
                <th colspan="2" style="text-align: left;width: 30px;">Folgas: <?php echo $funcionario['folgas'];?></th>
                <th colspan="2" style="text-align: left;width: 30px;"></th>
                <th colspan="2" style="text-align: right;width: 30px;font-size: 13px;">Total =></th>
                <th style="text-align: center;width: 30px;"><?php echo $funcionario['trabalhadas'];?></th>
                <th style="text-align: center;width: 30px;"><?php echo $funcionario['abonadas'];?></th>
                <th style="text-align: center;width: 30px;"><?php echo $funcionario['faltas'];?></th>
                <th style="text-align: center;width: 30px;"><?php echo $funcionario['extra'];?></th>
            </tr>
        </table>
        <br>
        <br>
        <br>
        <table style="font-family: arial;font-size: 11px;">
            <tr>
                <td style="width: 300px;text-align:center;">
                    ___________________________________________
                </td>
                <td style="width: 100px;">
                </td>
                <td style="width: 300px;text-align:center;">
                    _______________, ______ de _______________ de 2019
                </td>
            </tr>
            <tr>
                <td style="text-align:center;">
                    Assinatura do Funcionário
                </td>
                <td colspan="2"> </td>
            </tr>
        </table>
        <hr>
        <table style="font-family: arial;font-size: 10px;text-align: justify;">
            <tr>
                <td>
                    De conformidade com as Portarias MTB nº 3626, de 13/11/91, Art. 13, este cartão de ponto substitui, quando mencionado em seu cabeçalho o horário de trabalho e o dia do DSR do funcionário, para todos os efeitos legais, o Quadro de Horário de Trabalho e
                    a Ficha de Horário de Trabalho Externo.
                </td>
            </tr>
        </table>
    </div>
    <?php }?>
    
</body>

<script>
    $(document).ready(function() {
        print();
    });

    function imprimir(){
        window.print();
    }
</script>