<!DOCTYPE html>

<head>
<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
?>
</head>

<body>
    <div class="col-md-6 offset-md-3" style="background-color:#f9f6f6;">
        <table>
            <tr>
                <td style="width: 100px;">
                <img width="40px" src="<?php echo $this->basePath('img/logo-login.png') ?>" alt="Zend Framework 2"/>
                </td>
                <td style="width: 500px;">
                    <div style="text-align: center;">
                        <label style="font-family: Arial;font-size:30px;">
                            Folha de Ponto
                        </label>
                        <br>
                        <label style="font-family: Arial;font-size:18px;">
                            Período: 21/10/2019 à 31/10/2019
                        </label>
                    </div>
                </td>
                <td style="width: 100px;">

                </td>
            </tr>
        </table>

        <hr>
        <table style="font-family: Arial;font-size:11px;">
            <tr>
                <th style="text-align: right; width: 100px;">
                    Razão Social:
                </th>
                <td style="width: 230px;">
                    Tecnologia e Inovação ME
                </td>
                <th style="text-align: left; width: 55px;">
                    CNPJ:
                </th>
                <td colspan="3">
                    45.981.329/0001-19
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Endereço:
                </th>
                <td style="width: 230px;">
                    Rua Benjamin Constant
                </td>
                <th style="text-align: left; width: 55px;">
                    Número:
                </th>
                <td style="width: 90px;">
                    01
                </td>
                <th style="text-align: left; width: 45px;">
                    Bairro:
                </th>
                <td style="width: 70px;">
                    Centro
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    CEP:
                </th>
                <td style="width: 230px;">
                    18870-000
                </td>
                <th style="text-align: left; width: 55px;">
                    Cidade:
                </th>
                <td style="width: 90px;">
                    Fartura
                </td>
                <th style="text-align: left; width: 45px;">
                    UF:
                </th>
                <td style="width: 70px;">
                    SP
                </td>
            </tr>
        </table>
        <hr style="border: 1px solid black;">
        <table style="font-family: Arial;font-size:11px;">
            <tr>
                <th style="text-align: right; width: 100px;">
                    Código:
                </th>
                <td style="width: 230px;">
                    1
                </td>
                <th colspan="5" style="text-align: center;font-size:15px;">
                    Horário de Trabalho
                </th>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Nome:
                </th>
                <td style="width: 230px;">
                    Welligtom Gomes de Almeida
                </td>
                <th style="width: 55px;text-align: left;"> </th>
                <th colspan="2" style="text-align: center;">
                    1º Período
                </th>
                <th colspan="2" style="text-align: center;">
                    2º Período
                </th>

            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    PIS:
                </th>
                <td style="width: 230px;">
                    111.11111.11-1
                </td>
                <th style="width: 55px;text-align: left;">
                    Dia
                </th>
                <th style="text-align: center;width: 28px;">
                    Entrada
                </th>
                <th style="text-align: center;width: 28px;">
                    Saída
                </th>
                <th style="text-align: center;width: 28px;">
                    Entrada
                </th>
                <th style="text-align: center;width: 28px;">
                    Saída
                </th>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Cargo:
                </th>
                <td style="width: 230px;">
                    Programador Jr
                </td>
                <th style="width: 55px;text-align: left;">
                    Domingo
                </th>
                <td style="text-align: center;">
                    --
                </td>
                <td style="text-align: center;">
                    --
                </td>
                <td style="text-align: center;">
                    --
                </td>
                <td style="text-align: center;">
                    --
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Salário:
                </th>
                <td style="width: 230px;">
                    R$ 1650,00
                </td>
                <th style="width: 55px;text-align: left;">
                    Segunda
                </th>
                <td style="text-align: center;">
                    08:00
                </td>
                <td style="text-align: center;">
                    12:00
                </td>
                <td style="text-align: center;">
                    13:00
                </td>
                <td style="text-align: center;">
                    17:00
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;">
                    Admissão:
                </th>
                <td style="width: 230px;">
                    29/10/2019
                </td>
                <th style="width: 55px;text-align: left;">
                    Terça
                </th>
                <td style="text-align: center;">
                    08:00
                </td>
                <td style="text-align: center;">
                    12:00
                </td>
                <td style="text-align: center;">
                    13:00
                </td>
                <td style="text-align: center;">
                    17:00
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Quarta
                </th>
                <td style="text-align: center;">
                    08:00
                </td>
                <td style="text-align: center;">
                    12:00
                </td>
                <td style="text-align: center;">
                    13:00
                </td>
                <td style="text-align: center;">
                    17:00
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Quinta
                </th>
                <td style="text-align: center;">
                    08:00
                </td>
                <td style="text-align: center;">
                    12:00
                </td>
                <td style="text-align: center;">
                    13:00
                </td>
                <td style="text-align: center;">
                    17:00
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Sexta
                </th>
                <td style="text-align: center;">
                    08:00
                </td>
                <td style="text-align: center;">
                    12:00
                </td>
                <td style="text-align: center;">
                    13:00
                </td>
                <td style="text-align: center;">
                    17:00
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 100px;"></th>
                <td style="width: 230px;"></td>
                <th style="width: 55px;text-align: left;">
                    Sábado
                </th>
                <td style="text-align: center;">
                    --
                </td>
                <td style="text-align: center;">
                    --
                </td>
                <td style="text-align: center;">
                    --
                </td>
                <td style="text-align: center;">
                    --
                </td>
            </tr>

        </table>
        <hr style="border: 1px solid black;">
        <table style="font-family: Arial;font-size:11px;border:0px;border-collapse: inherit;border-spacing: 0px;">
            <tr>
                <th colspan="2"></th>
                <th colspan="2">1º Período</th>
                <th colspan="2">2º Período</th>
                <th colspan="2">3º Período</th>
                <th colspan="2">4º Período</th>
                <th colspan="2">5º Período</th>
                <th colspan="3"></th>
            </tr>
            <tr>
                <th colspan="2">Data</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 30px;">Ent</th>
                <th style="text-align: center;width: 30px;">Sai</th>
                <th style="text-align: center;width: 70px;">H. Trab.</th>
                <th style="text-align: center;width: 70px;">H. Abonada</th>
                <th style="text-align: center;width: 70px;">H. Falt.</th>
            </tr>
            <!-- PONTOS -->
            <!-- 1 -->
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">01/10</th>
                <th style="text-align: left;width: 30px;">ter</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">02/10</th>
                <th style="text-align: left;width: 30px;">qua</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">03/10</th>
                <th style="text-align: left;width: 30px;">qui</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">04/10</th>
                <th style="text-align: left;width: 30px;">sex</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">05/10</th>
                <th style="text-align: left;width: 30px;">sab</th>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">06/10</th>
                <th style="text-align: left;width: 30px;">dom</th>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">07/10</th>
                <th style="text-align: left;width: 30px;">seg</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">08/10</th>
                <th style="text-align: left;width: 30px;">ter</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">09/10</th>
                <th style="text-align: left;width: 30px;">qua</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">10/10</th>
                <th style="text-align: left;width: 30px;">qui</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">11/10</th>
                <th style="text-align: left;width: 30px;">sex</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">12/10</th>
                <th style="text-align: left;width: 30px;">sab</th>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">13/10</th>
                <th style="text-align: left;width: 30px;">dom</th>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">14/10</th>
                <th style="text-align: left;width: 30px;">seg</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">15/10</th>
                <th style="text-align: left;width: 30px;">ter</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">16/10</th>
                <th style="text-align: left;width: 30px;">qua</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">17/10</th>
                <th style="text-align: left;width: 30px;">qui</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">18/10</th>
                <th style="text-align: left;width: 30px;">sex</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">19/10</th>
                <th style="text-align: left;width: 30px;">sab</th>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">20/10</th>
                <th style="text-align: left;width: 30px;">dom</th>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">21/10</th>
                <th style="text-align: left;width: 30px;">seg</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">22/10</th>
                <th style="text-align: left;width: 30px;">ter</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">23/10</th>
                <th style="text-align: left;width: 30px;">qua</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">24/10</th>
                <th style="text-align: left;width: 30px;">qui</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">25/10</th>
                <th style="text-align: left;width: 30px;">sex</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">26/10</th>
                <th style="text-align: left;width: 30px;">sab</th>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;">--:--</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">27/10</th>
                <th style="text-align: left;width: 30px;">dom</th>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;">DSR</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">28/10</th>
                <th style="text-align: left;width: 30px;">seg</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">29/10</th>
                <th style="text-align: left;width: 30px;">ter</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th style="text-align: left;width: 30px;">30/10</th>
                <th style="text-align: left;width: 30px;">qua</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr style="background: #e6e6e6;">
                <th style="text-align: left;width: 30px;">31/10</th>
                <th style="text-align: left;width: 30px;">qui</th>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;">12:00</td>
                <td style="text-align: center;width: 30px;">13:00</td>
                <td style="text-align: center;width: 30px;">17:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;">08:00</td>
                <td style="text-align: center;width: 30px;"></td>
                <td style="text-align: center;width: 30px;"></td>
            </tr>
            <tr>
                <th colspan="2" style="text-align: left;width: 30px;">D. Trab.: 31</th>
                <th colspan="2" style="text-align: left;width: 30px;">D. Falt.: 0</th>
                <th colspan="2" style="text-align: left;width: 30px;">DSR: 4</th>
                <th colspan="2" style="text-align: left;width: 30px;">Folgas: 8</th>
                <th colspan="2" style="text-align: left;width: 30px;"></th>
                <th colspan="2" style="text-align: right;width: 30px;font-size: 13px;">Total =></th>
                <th style="text-align: center;width: 30px;">184:00</th>
                <th style="text-align: center;width: 30px;"></th>
                <th style="text-align: center;width: 30px;"></th>
            </tr>
        </table>
        <br>
        <br>
        <br>
        <table style="font-family: arial;font-size: 11px;">
            <tr>
                <td style="width: 300px;text-align:center;">
                    ___________________________________________
                </td>
                <td style="width: 100px;">
                </td>
                <td style="width: 300px;text-align:center;">
                    _______________, ______ de _______________ de 2019
                </td>
            </tr>
            <tr>
                <td style="text-align:center;">
                    Assinatura do Funcionário
                </td>
                <td colspan="2"> </td>
            </tr>
        </table>
        <hr>
        <table style="font-family: arial;font-size: 10px;text-align: justify;">
            <tr>
                <td>
                    De conformidade com as Portarias MTB nº 3626, de 13/11/91, Art. 13, este cartão de ponto substitui, quando mencionado em seu cabeçalho o horário de trabalho e o dia do DSR do funcionário, para todos os efeitos legais, o Quadro de Horário de Trabalho e
                    a Ficha de Horário de Trabalho Externo.
                </td>
            </tr>
        </table>
    </div>
</body>