<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Relatórios';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<label style="font-size:25px;color:#2c3b94;">Resultados</label>
<br>
<?php
    $funcionarios = $this->funcionarios;
    
    foreach ($funcionarios as $funcionario)
    {
?>
    <label><?php echo $funcionario->olha ?></label>


<?php        
    }
    
?>
