<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Relatórios';
$this->headTitle($title);

$info = $this->informacao;

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
    <label style="font-size:25px;color:#2c3b94;"><?= $this->relatorio; ?></label>
    <button class="btn btn-success float-right" onclick="javascript:print()" name="print">Imprimir relatório</button>
</div>
<table class="table table-striped" style="size:10">
<?php if ($info == 1){?>
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Sexo</th>
        <th>Data de Nascimento</th>
        <th>CPF</th>
        <th>Celular</th>
        <th>Função</th>
        <th>Data de Admissão</th>
    </tr>
    <?php
        $funcionarios = $this->funcionarios;
        
        foreach ($funcionarios as $funcionario)
        {
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($funcionario->id);?></td>
        <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
        <td><?php echo $this->escapeHtml($funcionario->sexo);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_nascimento);?></td>
        <td><?php echo $this->escapeHtml($funcionario->cpf);?></td>
        <td><?php echo $this->escapeHtml($funcionario->telefone_celular_1);?></td>
        <td><?php echo $this->escapeHtml($funcionario->funcao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_admissao);?></td>
    </tr>
    <?php        
        }
        
    ?>
<?php }elseif ($info == 2){?>
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Data de demissão</th>
        <th>Observação</th>
        <th>Função</th>
        <th>Data de Admissão</th>
    </tr>
    <?php
        $funcionarios = $this->funcionarios;
        foreach ($funcionarios as $funcionario)
        {
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($funcionario->id);?></td>
        <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_demissao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->observacao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->funcao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_admissao);?></td>
    </tr>
    <?php        
        }
        
    ?>
<?php }elseif ($info == 3){?>
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Sexo</th>
        <th>Data de Nascimento</th>
        <th>CPF</th>
        <th>Celular</th>
        <th>Função</th>
        <th>Data de Admissão</th>
    </tr>
    <?php
        $funcionarios = $this->funcionarios;
        
        foreach ($funcionarios as $funcionario)
        {
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($funcionario->id);?></td>
        <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
        <td><?php echo $this->escapeHtml($funcionario->sexo);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_nascimento);?></td>
        <td><?php echo $this->escapeHtml($funcionario->cpf);?></td>
        <td><?php echo $this->escapeHtml($funcionario->telefone_celular_1);?></td>
        <td><?php echo $this->escapeHtml($funcionario->funcao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_admissao);?></td>
    </tr>
    <?php        
        }
        
    ?>
<?php }elseif ($info == 4){?>
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Celular</th>
        <th>Função</th>
        <th>Início</th>
        <th>Fim</th>
        <th>Tipo</th>
    </tr>
    <?php
        $funcionarios = $this->funcionarios;
        
        foreach ($funcionarios as $funcionario)
        {
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($funcionario->id);?></td>
        <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
        <td><?php echo $this->escapeHtml($funcionario->telefone_celular_1);?></td>
        <td><?php echo $this->escapeHtml($funcionario->funcao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_inicio);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_fim);?></td>
        <td><?php echo $this->escapeHtml($funcionario->descricao);?></td>
    </tr>
    <?php        
        }
        
    ?>
<?php }elseif ($info == 5){?>
<tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Sexo</th>
        <th>Data de Nascimento</th>
        <th>CPF</th>
        <th>Celular</th>
        <th>Função</th>
        <th>Data de Admissão</th>
    </tr>
    <?php
        $funcionarios = $this->funcionarios;
        
        foreach ($funcionarios as $funcionario)
        {
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($funcionario->id);?></td>
        <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
        <td><?php echo $this->escapeHtml($funcionario->sexo);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_nascimento);?></td>
        <td><?php echo $this->escapeHtml($funcionario->cpf);?></td>
        <td><?php echo $this->escapeHtml($funcionario->telefone_celular_1);?></td>
        <td><?php echo $this->escapeHtml($funcionario->funcao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_admissao);?></td>
    </tr>
    <?php        
        }
        
    ?>
<?php }else{?>
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Sexo</th>
        <th>Data de Nascimento</th>
        <th>CPF</th>
        <th>Celular</th>
        <th>Função</th>
        <th>Data de Admissão</th>
    </tr>
    <?php
        $funcionarios = $this->funcionarios;
        
        foreach ($funcionarios as $funcionario)
        {
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($funcionario->id);?></td>
        <td><?php echo $this->escapeHtml($funcionario->nome);?></td>
        <td><?php echo $this->escapeHtml($funcionario->sexo);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_nascimento);?></td>
        <td><?php echo $this->escapeHtml($funcionario->cpf);?></td>
        <td><?php echo $this->escapeHtml($funcionario->telefone_celular_1);?></td>
        <td><?php echo $this->escapeHtml($funcionario->funcao);?></td>
        <td><?php echo $this->escapeHtml($funcionario->data_admissao);?></td>
    </tr>
    <?php        
        }
    }
    ?>
</table>
