<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- Scripts -->
        <?php echo $this->headScript()
            // ->prependFile($this->basePath() . 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')
            // ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery-3.4.1.min.js')
            //   ->prependFile($this->basePath() . 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')
            
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            // ->prependFile($this->basePath() . 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')
        ; ?>

        <style>
            
            * {
                margin: 0;
                padding:0;
            }

            /* para garantir que estes elementos ocuparão toda a tela */
            body, html {
                width: 100%;
                height: 100%;
                font-family: Arial, Tahoma, sans-serif;
            }

            #fundo-externo {
                overflow: hidden; /* para que não tenha rolagem se a imagem de fundo for maior que a tela */
                width: 100%;
                height: 100%;
                position: relative; /* criamos um contexto para posicionamento */
            }

            #fundo {
                position: fixed; /* posição fixa para que a possível rolagem da tela não revele espaços em branco */
                width: 100%;
                height: 100%;
            }

            #fundo img {
                width: 100%; /* com isso imagem ocupará toda a largura da tela. Se colocarmos height: 100% também, a imagem irá distorcer */
                position: absolute;
            }

            #site {
                position: absolute;
                top: 40px;
                left: 50%;
                width: 560px;
                padding: 20px;
                margin-left: -300px; /* por causa do posicionamento absoluto temos que usar margem negativa para centralizar o site */
                background: #FFF; /* fundo branco para navegadores que não suportam rgba */
                background: rgba(255,255,255,0.8); /* fundo branco com um pouco de transparência */
            }

            p {
                margin-bottom: 1.5em;
            }

            .footer {
                bottom: 0;
                position: fixed;
                width: 100%;
                text-align: center;
            }

            .div-def{
                margin-bottom:10px;
            }
            .texto-rodape {
                position: absolute;
                z-index: 999;
                left: 0;
                right: 0;
                top: 45%;
                display: inline;
                text-align: center;
            }
            a:link{ 
                text-decoration:none; 
            } 
        </style>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="/js/bootstrap.min.js" ></script>
        <script src="/js/jquery.mask.js" ></script>
        <script src="/js/jquery.maskmoney.js" ></script>
        <script src="/js/sweetalert.js" ></script>
    
    </head>
    <body class="position-relative" style="min-height: 100vh;">
        <div style="height: 100vh">
        <?php
            if(isset($_SESSION['funcionario']))
            {
        ?>
        <nav class="navbar navbar-expand-md navbar-principal navbar-light">
            <div class="container">
                <?php 
                    if($_SESSION['funcionario']->perfil != 1)
                    {
                ?>
                <a class="navbar-brand font-weight-bold white-text" style="text-color:#ffffff;color:#ffffff;" href="<?php echo $this->url('ponto') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                <?php 
                    }
                    else
                    {
                ?> 
                <a class="navbar-brand font-weight-bold white-text" style="text-color:#ffffff;color:#ffffff;" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                <?php 
                    }
                ?>    
                <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                    <ul class="navbar-nav mr-auto" >
                        <?php 
                            if($_SESSION['funcionario']->perfil != 1)
                            {
                        ?>
                        <li class="nav-item">
                            <a class="nav-link" href=" <?php echo $this->url('ponto'); ?>
                                "><b style="text-color:#ffffff;color:#ffffff;">Registrar Ponto</b></a>
                        </li>
                        <?php 
                            }
                        ?>     
                        <?php 
                            if($_SESSION['funcionario']->perfil == 1)
                            {
                        ?>                   
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b style="text-color:#ffffff;color:#ffffff;">Empresa</b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="<?php echo $this->url('empresas');?>">Cadastro</a>
                            <a class="dropdown-item" href="<?php echo $this->url('variaveisEmpresa'); ?>">Configurações</a>
                            </div>
                        </li>
                        <?php 
                            }
                        ?> 
                        <?php 
                            if($_SESSION['funcionario']->perfil != 3)
                            {
                        ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b style="text-color:#ffffff;color:#ffffff;">Funcionários</b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="<?php echo $this->url('funcionarios') ?>">Cadastros</a>
                            <a class="dropdown-item" href="<?php echo $this->url('atestados'); ?>">Atestados</a>
                            <a class="dropdown-item" href="<?php echo $this->url('afastarFuncionario'); ?>">Afastar Funcionário</a>
                            </div>
                        </li>
                        <?php 
                            }
                        ?> 
                        <?php 
                            if($_SESSION['funcionario']->perfil == 1)
                            {
                        ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b style="text-color:#ffffff;color:#ffffff;">Relatórios</b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="<?php echo $this->url('relatorios',array('action'=>'consulta-funcionarios')); ?>">Folha de Ponto</a>
                            <a class="dropdown-item" href="<?php echo $this->url('relatorios',array('action'=>'index')); ?>">Relatório Geral</a>
                            </div>
                        </li>
                        <?php 
                            }
                        ?>   
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('funcionarios',array('action'=>'meu-perfil')) ?>"><b style="text-color:#ffffff;color:#ffffff;">Meu Perfil</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('login') ?>"><b style="text-color:#ffffff;color:#ffffff;">Sair</b></a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
        <nav class="navbar navbar-expand-md navbar-saudacao" style="background:#dbdbce;">
            <div class="container">
                <div>
                    Seja bem vindo 
                    <b style="color:#5d669c;text-align:left;">
                        <?php echo isset($_SESSION['funcionario']->nome)?$_SESSION['funcionario']->nome:''; ?>
                    </b>
                </div> 
            </div>
        </nav>
        <?php
            }
        ?>

        <div class="container main-content col-md-10" style="padding-bottom: 5em">
            <?php echo $this->content; ?>
        </div>
        <footer class="position-absolute navbar-fixed-bottom">
            <p class="texto-rodape">&copy; 2019 - <?php echo date('Y') ?> by FATEC - Ourinhos <?php echo $this->translate('All rights reserved.') ?></p>
            <div class="col-md-12 px-0 mt-3">
                <img src="/img/rodape.svg" class="img-fluid" alt="">
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </div>
    </body>
</html>