<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/css/bootstrap.min.css')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery-3.4.1.min.js')
            ->prependFile($this->basePath() . '/js/jquery.mask.js')
            ->prependFile($this->basePath() . '/js/jquery.mask.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <style>
            .footer {
                bottom: 0;
                position: fixed;
                width: 100%;
                text-align: center;
            }

            .div-def{
                margin:10px;
            }
        </style>

    </head>
    <body>
        <?php
            if(isset($_SESSION['funcionario']))
            {
        ?>
        <nav class="navbar navbar-expand-md navbar-principal navbar-light">
            <div class="container">
                <a class="navbar-brand font-weight-bold white-text" style="text-color:#ffffff;color:#ffffff;" href="<?php echo $this->url('ponto') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                    <ul class="navbar-nav mr-auto" >
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b style="text-color:#ffffff;color:#ffffff;">Empresa</b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="<?php echo $this->url('empresas',
                                    array('action'=>'update', 'id' => $_SESSION['empresa']));?>">Cadastro</a>
                            <a class="dropdown-item" href="<?php echo $this->url('variaveisEmpresa', array('action'=>'update', 'id' => $_SESSION['variaveisEmpresa'])); ?>">Configurações</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b style="text-color:#ffffff;color:#ffffff;">Funcionários</b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="<?php echo $this->url('funcionarios') ?>">Cadastro de Funcionário</a>
                            <a class="dropdown-item" href="<?php echo $this->url('atestados'); ?>">Abonar Falta</a>
                            <a class="dropdown-item" href="#">Afastar Funcionário</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><b style="text-color:#ffffff;color:#ffffff;">Relatórios</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><b style="text-color:#ffffff;color:#ffffff;">Meu Perfil</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('login') ?>"><b style="text-color:#ffffff;color:#ffffff;">Sair</b></a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
        <nav class="navbar navbar-expand-md navbar-saudacao" style="background:#dbdbce;">
            <div class="container">
                <div>
                    Seja bem vindo 
                    <b style="color:#5d669c;text-align:left;">
                        <?php echo isset($_SESSION['funcionario']->nome)?$_SESSION['funcionario']->nome:''; ?>
                    </b>
                </div> 
            </div>
        </nav>
        <?php
            }
        ?>

        <div class="container main-content col-md-10">
            <?php echo $this->content; ?>
            
            <div class="" align="center">
                <hr>
                <p>&copy; 2019 - <?php echo date('Y') ?> by FATEC - Ourinhos <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>