<?php

$title = 'Cadastrar nova empresa';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('empresa', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();