<script>
    $(document).ready(function(){
        $('#horas_abonadas').mask('0', {reverse: false});
    });
</script>

<?php

$title = 'Atestados';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<label style="font-size:25px;color:#2c3b94;">Cadastrar</label>
<?php
$funcionario = $this->funcionario;

$form = $this->form;
$form->setAttribute('action', $this->url('atestados', array('action' => 'create','id' => $funcionario->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('funcionario_id'));
?>
<br>
<div class="col-md-12 form-inline">
<div class="col-md-12">
<table class="col-md-12" style="background:#f3f3f0;">
    <tr>
        <th>Funcionário</th>
        <th>CPF</th>
    </tr>
    <tr>
        <td>
            <?php echo $funcionario->nome; ?>
        </td>
        <td>
            <?php echo $funcionario->cpf; ?>
        </td>
    </tr>
    <tr>
        <th>Função</th>
        <th>Data de Nascimento</th>
    </tr>
    <tr>
        <td>
            <?php echo $funcionario->funcao; ?>
        </td>
        <td>
            <?php echo $funcionario->data_nascimento; ?>
        </td>
    </tr>
</table>
<br>
</div>

<div class="col-md-3">
    <div>
        Data*
    </div>
    <?php echo $this->formRow($form->get('data')); ?>
</div>
<div class="col-md-3">
    <div>
        Horas Abonadas*
    </div>
    <?php echo $this->formRow($form->get('horas_abonadas')); ?>
</div>
<div class="col-md-12">
    <div>
        Motivo*
    </div>
    <?php echo $this->formRow($form->get('motivo')); ?>
</div>
<br>
<div class="col-md-12">
    <br>
    <a href="<?php echo $this->url('atestados',
                    array('action'=>'index'));?>" class="btn btn-danger btn-lg active col-md-2 " role="button" aria-pressed="true">Cancelar</a>
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
</div>

<?php
echo $this->form()->closeTag();