<?php
// module/Album/view/album/album/index.phtml:

$title = 'Atestados';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('atestados', array('action'=>'consultaFuncionarios'));?>">+ Adicionar novo atestado</a>
</p>

<table class="table">
<tr>
    <th>Código</th>
    <th>Funcionário</th>
    <th>data</th>
    <th>Horas Abonadas</th>
</tr>
<?php foreach ($atestados as $atestado) : ?>
<tr>
    <td><?php echo $this->escapeHtml($atestado->id);?></td>
    <td><?php echo $this->escapeHtml($atestado->funcionario_id);?></td>
    <td><?php echo $this->escapeHtml($atestado->data);?></td>
    <td><?php echo $this->escapeHtml($atestado->horas_abonadas);?></td>
    <td>
        <a href="<?php echo $this->url('atestados',
            array('action'=>'update', 'id' => $atestado->id));?>">Alterar</a>
        <a href="<?php echo $this->url('atestados',
            array('action'=>'delete', 'id' => $atestado->id));?>">Excluir</a>
    </td>
</tr>
<?php endforeach; ?>
</table>