<?php
// module/Album/view/album/album/index.phtml:

$title = 'Pontos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('ponto', array('action'=>'create'));?>">+ Adicionar nova ponto</a>
</p>

<table class="table">
<tr>
    <th>Código</th>
    <th>Funcionario</th>
    <th>Entrada</th>
    <th>Saída</th>
</tr>
<?php foreach ($ponto as $ponto) : ?>
<tr>
    <td><?php echo $this->escapeHtml($ponto->id);?></td>
    <td><?php echo $this->escapeHtml($ponto->funcionario_id);?></td>
    <td><?php echo $this->escapeHtml($ponto->hora_entrada);?></td>
    <td><?php echo $this->escapeHtml($ponto->hora_saida);?></td>
    <td>
        <a href="<?php echo $this->url('ponto',
            array('action'=>'update', 'id' => $ponto->id));?>">Alterar</a>
        <a href="<?php echo $this->url('ponto',
            array('action'=>'delete', 'id' => $ponto->id));?>">Excluir</a>
    </td>
</tr>
<?php endforeach; ?>
</table>