<?php
// module/Album/view/album/album/index.phtml:

$title = 'Empresas';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('empresas', array('action'=>'create'));?>">+ Adicionar nova empresa</a>
</p>

<table class="table">
<tr>
    <th>Código</th>
    <th>Razão Social</th>
    <th>CNPJ</th>
    <th>Data de Cadastro</th>
</tr>
<?php foreach ($empresas as $empresa) : ?>
<tr>
    <td><?php echo $this->escapeHtml($empresa->id);?></td>
    <td><?php echo $this->escapeHtml($empresa->razao_social);?></td>
    <td><?php echo $this->escapeHtml($empresa->cnpj);?></td>
    <td><?php echo $this->escapeHtml($empresa->data_cadastro);?></td>
    <td>
        <a href="<?php echo $this->url('empresas',
            array('action'=>'update', 'id' => $empresa->id));?>">Alterar</a>
        <a href="<?php echo $this->url('empresas',
            array('action'=>'delete', 'id' => $empresa->id));?>">Excluir</a>
    </td>
</tr>
<?php endforeach; ?>
</table>