<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Alterar Empresa';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'empresas',
    array(
        'action' => 'update',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('razao_social'));
echo $this->formRow($form->get('cnpj'));
echo $this->formRow($form->get('telefone_fixo'));
echo $this->formRow($form->get('telefone_celular_1'));
echo $this->formRow($form->get('telefone_celular_2'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('data_cadastro'));
?>
<br>
<div class="col-md-12">
    <h5>Endereço</h5>
</div>
<hr>
<div class="col-md-6 div-def">
    <?php   echo $this->formRow($form->get('cep')); ?>
</div>
<div class="col-md-6 div-def float-right">
    <?php   echo $this->formRow($form->get('cidade')); ?>
</div>
<div class="col-md-12 div-def">
    <?php   echo $this->formRow($form->get('uf')); ?>
</div>
<div class="col-md-12 div-def">
    <?php   echo $this->formRow($form->get('logradouro')); ?>
</div>
<div class="col-md-12 div-def">
    <?php   echo $this->formRow($form->get('numero')); ?>
</div>
<div class="col-md-12 div-def">
    <?php   echo $this->formRow($form->get('bairro')); ?>
</div>
<div class="col-md-12 div-def">
    <?php   echo $this->formRow($form->get('complemento')); ?>
</div>
<br>
<div class="col-md-12">
    <div class="">
        <a href="<?php echo $this->url('empresas',
                    array('action'=>'index'));?>" class="btn btn-danger btn-lg active col-md-2 " role="button" aria-pressed="true">Cancelar</a>
        <?php   echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>