<?php
// module/Album/view/album/album/index.phtml:

$title = 'Variaveis de Empresa';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th>Código</th>
    <th>Empresa ID</th>
    <th></th>
</tr>
<?php foreach ($variaveisEmpresa as $variaveis) : ?>
<tr>
    <td><?php echo $this->escapeHtml($variaveis->id);?></td>
    <td><?php echo $this->escapeHtml($variaveis->empresa_id);?></td>
    <td>
        <a href="<?php echo $this->url('variaveisEmpresa',
            array('action'=>'update', 'id' => $variaveis->id));?>">Alterar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>