<script>
    $(document).ready(function(){
        $('.hora').mask('00:00', {reverse: false});
        $('#horas_semanais').mask('00', {reverse: false});
    });
</script>

<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Configurações';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<label style="font-size:25px;color:#2c3b94;">Alterar</label>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'variaveisEmpresa',
    array(
        'action' => 'update',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<br>
<div class="col-md-12 form-inline">
<div class="col-md-12">
    <h5>Horário de Trabalho</h5>
    <hr>
</div>
<hr>
<div class="col-md-3 div-def">
    <div>
        Entrada*
    </div>
    <?php   echo $this->formRow($form->get('ent_1')); ?>
</div>
<div class="col-md-3 div-def">
    <div>
        Intervalo*
    </div>
    <?php   echo $this->formRow($form->get('sai_1')); ?>
</div>
<div class="col-md-3 div-def">
    <div>
        Retorno*
    </div>
    <?php   echo $this->formRow($form->get('ent_2')); ?>
</div>
<div class="col-md-3 div-def">
    <div>
        Saída*
    </div>
    <?php   echo $this->formRow($form->get('sai_2')); ?>
</div>

<br>
<div class="col-md-12">
    <br>
    <h5>Horário de Trabalho aos Sábados</h5>
    <hr>
</div>
<hr>
<div class="col-md-3 div-def">
    <div>
        Entrada
    </div>
    <?php   echo $this->formRow($form->get('ent_sab_1')); ?>
</div>
<div class="col-md-3 div-def">
    <div>
        Intervalo
    </div>
    <?php   echo $this->formRow($form->get('sai_sab_1')); ?>
</div>
<div class="col-md-3 div-def">
    <div>
        Retorno
    </div>
    <?php   echo $this->formRow($form->get('ent_sab_2')); ?>
</div>
<div class="col-md-3 div-def">
    <div>
        Saída
    </div>
    <?php   echo $this->formRow($form->get('sai_sab_2')); ?>
</div>
<br>
<div class="col-md-12">
    <br>
    <h5>Carga Horária</h5>
    <hr>
</div>
<hr>
<div class="col-md-3 div-def">
    <div>
        Horas Semanais*
    </div>
    <?php   echo $this->formRow($form->get('horas_semanais')); ?>
</div>

<div class="col-md-12">
    <br>
    <a href="<?php echo $this->url('variaveisEmpresa',
                    array('action'=>'index'));?>" class="btn btn-danger btn-lg active col-md-2 " role="button" aria-pressed="true">Cancelar</a>
    <?php   echo $this->formSubmit($form->get('submit')); ?>
</div>
</div>
<?php
echo $this->form()->closeTag();
?>