<h1>
    Seja Bem Vindo ao Work Clock
</h1>
<br>
<br>
<div class="form-inline col-md-12">

    <a href="<?php echo $this->url('empresas');?>" class="col-md-5" style="background-color:#4c76c3;height:200px;font-weight: bold;font-size: 30px;margin: 10px;text-align: center;" >
        <div style="margin-top: 80px;color:#ffff;">
            Empresa
        </div>
    </a>
    <a href="<?php echo $this->url('funcionarios');?>" class="col-md-5" style="background-color:#3fab5b;height:200px;font-weight: bold;font-size: 30px;margin: 10px;text-align: center;">
        <div style="margin-top: 80px;color:#ffff;">
            Funcionários
        </div>
    </a>
    <a href="<?php echo $this->url('relatorios');?>" class="col-md-5" style="background-color:#bf4d4d;height:200px;font-weight: bold;font-size: 30px;margin: 10px;text-align: center;">
        <div style="margin-top: 80px;color:#ffff;">
            Relatórios
        </div>
    </a>
</div>
